### ISSUE TITLE
shell example doesn't work

### ISSUE THREAD

**Issue by dlebauer** [btford/write-good#44] opened 2015-05-26 00:02 UTC
If I create a file with the example sentence, and run write-good I do not get any output:

``` sh
$ echo "So the cat was stolen." > test.md
$ write-good test.md 
```

I expected the same output as in the README, but do not see it.

**Comment by icyflame** [comment] 2015-06-19 05:00
@dlebauer 

It does work for me, can you post the output that you got?

**Comment by icyflame** [comment] 2015-06-19 05:04
@dlebauer 

Also, could you clarify as to what you mean by : -

> do not get any output

**Comment by tshirtman** [comment] 2017-09-21 12:17
i get the same issue.

    writegood --text="borken english sentence, with long rambling word, mistakes, blah"

i get literally no output.

strace seems to indicate it does some work, produce annotations, etc, but nothing is printed…

**Comment by RichardLitt** [comment] 2017-09-21 15:34
@dlebauer I am unable to replicate.

```
11:32 ~/src/write-good (master) * 🐕  echo "So the cat was stolen." > test.md
11:32 ~/src/write-good (master) * 🐕  node bin/write-good.js test.md
In test.md
=============
So the cat was stolen.
^^
"So" adds no meaning on line 1 at column 0
-------------
So the cat was stolen.
           ^^^^^^^^^^
"was stolen" may be passive voice on line 1 at column 11
```

@tshirtman I believe it just didn't have an issue with your example.

```
🐕  write-good --text="borken english sentence, with long rambling word, should have been  mistakes, blah"
11:32 ~/src/write-good (master) * 🐕  write-good --text="borken english sentence, with long rambling word, should have been defined  mistakes, blah"
In text
=============
mbling word, should have been defined  mistakes, blah
                         ^^^^^^^^^^^^
"been defined" may be passive voice on line 1 at column 62
```

I think this is actually expected behavior.

**Comment by tshirtman** [comment] 2017-09-22 15:19
Ok, i retried now with the passive sentence from the readme, and got the issue, i can only assume i tested wrong yesterday, sorry!

**Comment by RichardLitt** [comment] 2017-09-22 18:48
Unable to replicate original bug. @dlebauer closing this due to time since filed - let us know if we should reopen.

**Closed by RichardLitt** 2017-09-22 18:48 UTC
